on:
  workflow_call:
    inputs:
      deno-version:
        type: string
        required: true
    

jobs:
  build:
    runs-on: ubuntu-latest-xxl
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: deno-arm-amazon-linux-2
          build-args: DENO_VERSION=${{ inputs.deno-version }}
          platforms: linux/arm64
      
      - name: Extract deno binary from image
        run: |
          containerId=$(docker create deno-arm-amazon-linux-2)
          docker cp $containerId:/deno/target/release/deno deno
          docker rm $containerId

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deno
          path: deno
          retention-days: 1
