on:
  workflow_call:
    inputs:
      deno-version:
        type: string
        required: true
    

jobs:
  build:
    runs-on: ubuntu-latest-l
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Build Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: false
      #     load: true
      #     tags: deno-arm-amazon-linux-2
      #     build-args: DENO_VERSION=${{ inputs.deno-version }}
      #     platforms: linux/arm64
      
      # - name: Extract deno binary from image
      #   run: |
      #     containerId=$(docker create deno-arm-amazon-linux-2)
      #     docker cp $containerId:/deno/target/release/deno deno
      #     docker rm $containerId

      - name: create deno file
        run: echo "mock deno binary" > deno

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deno-aarch64-amazon-linux-2-gnu
          path: deno
          retention-days: 1

      - name: Zip binary
        run: zip deno-aarch64-amazon-linux-2-gnu.zip deno

      - name: Create release
        run: gh release create "v$DENO_VERSION" --title "v$DENO_VERSION"
        env:
          DENO_VERSION: ${{ inputs.deno-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add binary file to release
        run: gh release upload "v$DENO_VERSION" deno-aarch64-amazon-linux-2-gnu.zip
        env:
          DENO_VERSION: ${{ inputs.deno-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
