on:
  workflow_dispatch:
    inputs:
      deno-version:
        type: string
        required: true
        description: Deno version (including leading v)

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      deno-version: ${{ inputs.deno-version }}
